name: CI
on:
- pull_request

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }})
    strategy:
      matrix:
        python_version:
        - 2.7
        - 3.5
        ansible:
        - stable-2.4
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/hpe/oneview

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install future
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check
      - name: Install ansible test
        run: |
          git clone https://github.com/ansible/ansible.git
          source ./ansible/hacking/env-setup
          pip install pyyaml jinja2 nose pytest passlib pycrypto six voluptuous
      - name: Setup environment for Ansible build
        run: |
         echo "ANSIBLE_LIBRARY=$PWD/library" >> $GITHUB_ENV
         echo "PYTHONPATH=$ANSIBLE_LIBRARY:$PYTHONPATH" >> $GITHUB_ENV
         touch examples/vars/config.yml
         ./build.sh
        
        
 
      

 
