name: CI
on:
- pull_request

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible_version }})
    strategy:
      matrix:
        python_version: [2.7, 3.5]
        ansible_version: [2.1.5.0, 2.2.2.0, 2.3.0.0, 2.4.0.0]
      
        
    
 
